version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-chatbot/personal-chatbot
    overwrite: yes
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: scripts/clean_install_dir.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root